language: c
matrix:
  include:
    - os: linux
    - os: osx
    - os: windows
      env: MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild.exe"
git:
  submodules: true

before_script:
  
script:
  - mkdir build
  - cd build
  - cmake ..
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then "$MSBUILD_PATH" libwad.sln; else make; fi