language: c
os:
  - linux
  - osx
  - windows
compiler:
  - clang
  - gcc
git:
  submodules: true
script:
  - mkdir build
  - cd build
  - cmake ..
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then msbuild libwad.sln; else make; fi